import { Camera, BookOpen, ChefHat, Search } from "lucide-react";

export const SITE_STATS = [
  { label: "Free Scans", val: "10/mo" },
  { label: "Recipes Generated", val: "1M+" },
  { label: "Cost to Start", val: "$0" },
  { label: "App Store Rating", val: "4.9" },
];

export const FEATURES = [
  {
    title: "Scan Your Pantry",
    description:
      "Photo recognition that actually works. Know what you have instantly.",
    icon: Camera,
    limit: "10 scans/mo free",
  },
  {
    title: "AI Chef Suggestions",
    description:
      "Turn random ingredients into a gourmet meal. Zero food waste.",
    icon: ChefHat,
    limit: "5 meals/mo free",
  },
  {
    title: "Search Any Dish",
    description:
      "Find any recipe instantly. Filter by cuisine, time, or dietary needs.",
    icon: Search,
    limit: "Unlimited searches",
  },
  {
    title: "Digital Cookbook",
    description: "Save your favorites. Export as PDF. Share with family.",
    icon: BookOpen,
    limit: "3 saves/mo free",
  },
];

export const HOW_IT_WORKS_STEPS = [
  {
    step: "01",
    title: "Scan",
    desc: "Point camera at fridge. AI identifies ingredients.",
  },
  {
    step: "02",
    title: "Select",
    desc: "Choose a generated recipe based on your mood.",
  },
  {
    step: "03",
    title: "Savor",
    desc: "Follow simple steps. Eat delicious food.",
  },
];

// Helper function for category emojis
export function getCategoryEmoji(category) {
  const emojiMap = {
    Beef: "🥩",
    Chicken: "🍗",
    Dessert: "🍰",
    Lamb: "🍖",
    Miscellaneous: "🍴",
    Pasta: "🍝",
    Pork: "🥓",
    Seafood: "🦐",
    Side: "🥗",
    Starter: "🥟",
    Vegan: "🥬",
    Vegetarian: "🥕",
    Breakfast: "🍳",
    Goat: "🐐",
  };
  return emojiMap[category] || "🍽️";
}

// Helper function for country flags
export function getCountryFlag(country) {
  const emojiMap = {
    Afghan: "🕌",
    Albanian: "🦅",
    Algerian: "🏜️",
    Andorran: "⛰️",
    Angolan: "🐆",
    "Antiguan, Barbudan": "🏖️",
    Argentine: "⚽",
    Armenian: "🍑",
    Aruban: "🏝️",
    Australian: "🦘",
    Austrian: "🏔️",
    Azerbaijani: "🔥",
    Bahamian: "🐚",
    Bahraini: "🌴",
    Bangladeshi: "🐅",
    Barbadian: "🍹",
    Belarusian: "🦬",
    Belgian: "🍟",
    Belizean: "🏝️",
    Beninese: "🦁",
    Bermudian: "🔱",
    Bhutanese: "🐉",
    Bolivian: "🦙",
    "Bosnian, Herzegovinian": "🕌",
    Motswana: "🦁",
    Brazilian: "⚽",
    Bruneian: "🕌",
    Bulgarian: "🌹",
    Burkinabe: "🧣",
    Burundian: "🥁",
    Cambodian: "🛕",
    Cameroonian: "🦁",
    Canadian: "🍁",
    "Cape Verdian": "🎵",
    Caymanian: "🐢",
    "Central African": "🐘",
    Chadian: "🐫",
    Chilean: "🏔️",
    Chinese: "🐉",
    Colombian: "☕",
    "Costa Rican": "☕",
    Croatian: "⚽",
    Cuban: "🚬",
    Cypriot: "🏺",
    Czech: "🍺",
    Danish: "👑",
    Djibouti: "🐫",
    Dominican: "⚾",
    Congolese: "🦍",
    Ecuadorean: "🌋",
    Egyptian: "🐫",
    Salvadoran: "🌋",
    "Equatorial Guinean": "🌴",
    Eritrean: "🐪",
    Estonian: "🏛️",
    Ethiopian: "☕",
    Faroese: "🐑",
    Fijian: "🌊",
    Finnish: "☃️",
    French: "🥐",
    Gabonese: "🦍",
    Gambian: "🦜",
    Georgian: "🍇",
    German: "🍺",
    Ghanaian: "🌟",
    Gibraltar: "🐒",
    Greek: "🏛️",
    Greenlandic: "🐻‍❄️",
    Grenadian: "🌶️",
    Guadeloupian: "🦋",
    Guamanian: "🌊",
    Guatemalan: "🦜",
    "Channel Islander": "🐄",
    Guinean: "🍌",
    "Guinea-Bissauan": "🌴",
    Guyanese: "💎",
    Haitian: "🎨",
    Honduran: "🦜",
    "Hong Konger": "🏙️",
    Hungarian: "🌶️",
    Icelander: "❄️",
    Indian: "🪷",
    Indonesian: "🐉",
    Iranian: "🕌",
    Iraqi: "🌴",
    Irish: "☘️",
    Israeli: "🕎",
    Italian: "🍕",
    Ivorian: "🐘",
    Jamaican: "🌴",
    Japanese: "🗾",
    Jordanian: "🏜️",
    Kazakhstani: "🐎",
    Kenyan: "🦒",
    Kosovar: "🦅",
    Kuwaiti: "🐪",
    Kirghiz: "🐎",
    Laotian: "🐘",
    Latvian: "🌾",
    Lebanese: "🍢",
    Mosotho: "🏔️",
    Liberian: "🌴",
    Libyan: "🐫",
    Liechtensteiner: "👑",
    Lithuanian: "🌾",
    Luxembourger: "🦁",
    Malagasy: "🐒",
    Malawian: "🦁",
    Malaysian: "🌺",
    Maldivan: "🏝️",
    Malian: "🎵",
    Maltese: "🏺",
    Mauritian: "🐦",
    Mexican: "🌮",
    Moldovan: "🍇",
    Mongolian: "🐎",
    Montenegrin: "🏔️",
    Moroccan: "🕌",
    Mozambican: "🐘",
    Burmese: "🛕",
    Namibian: "🏜️",
    Nepalese: "🏔️",
    Dutch: "🌷",
    "New Zealander": "🥝",
    Nicaraguan: "🌋",
    Nigerien: "🐪",
    Nigerian: "🦅",
    "North Korean": "⭐",
    Macedonian: "🦁",
    Norwegian: "❄️",
    Omani: "🌊",
    Pakistani: "🏔️",
    Palestinian: "🍉",
    Panamanian: "🐟",
    "Papua New Guinean": "🦜",
    Paraguayan: "⚽",
    Peruvian: "🦙",
    Filipino: "🌴",
    Polish: "🦅",
    Portuguese: "🚢",
    "Puerto Rican": "🎵",
    Qatari: "🐪",
    Romanian: "🐺",
    Russian: "❄️",
    Rwandan: "🦍",
    "Saint Lucian": "🏝️",
    Samoan: "🌊",
    Sammarinese: "🏔️",
    "Saudi Arabian": "🕋",
    Senegalese: "🦁",
    Serbian: "🦅",
    Seychellois: "🐢",
    "Sierra Leonean": "🦁",
    Singaporean: "🦁",
    Slovak: "🏔️",
    Slovene: "🐝",
    "Solomon Islander": "🐟",
    Somali: "🐪",
    "South African": "🦁",
    "South Korean": "⚡",
    "South Sudanese": "🦒",
    Spanish: "💃",
    "Sri Lankan": "🐘",
    Sudanese: "🐫",
    Surinamer: "🐒",
    Swedish: "🦌",
    Swiss: "🧀",
    Syrian: "🏛️",
    Taiwanese: "🏙️",
    Tadzhik: "🏔️",
    Tanzanian: "🦒",
    Thai: "🛕",
    Togolese: "🦁",
    Tongan: "🌊",
    Trinidadian: "🥁",
    Tunisian: "🏜️",
    Turkish: "🧿",
    Turkmen: "🐎",
    Tuvaluan: "🌊",
    Ugandan: "🦍",
    Ukrainian: "🌻",
    Emirati: "🏙️",
    British: "👑",
    American: "🗽",
    Uruguayan: "⚽",
    Uzbekistani: "🕌",
    "Ni-Vanuatu": "🌊",
    Venezuelan: "🌞",
    Vietnamese: "🍜",
    Yemeni: "🏜️",
    Zambian: "🦁",
    Zimbabwean: "🦁",
  };

  return emojiMap[country] ?? "🌍";
}